apiVersion: v1
kind: Service
metadata:
  labels:
    app: app2
  name: app2-svc
  namespace: default
spec:
  ports:
  - name: serve
    port: 80
    targetPort: serve
  selector:
      app: app2
  type: NodePort
