apiVersion: v1
kind: Service
metadata:
  labels:
    app: app
  name: app-svc
  namespace: app2
spec:
  ports:
  - name: serve
    port: 80
    targetPort: serve
  selector:
      app: app
  type: NodePort