apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test
spec:
  rules:
  - http:
      paths:
      - path: /foo
        backend:
          serviceName: app1-svc
          servicePort: 80
      - path: /bar
        backend:
          serviceName: app2-svc
          servicePort: 80