kind: PersistentVolume
apiVersion: v1
metadata:
  name: ghost-disk
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: ghost-disk
    fsType: ext4