apiVersion: v1
kind: Service
metadata:
  labels:
    app: ghost
  name: ghost-svc
  namespace: default
spec:
  ports:
  - name: serve
    port: 80
    targetPort: serve
  selector:
      app: ghost
  type: LoadBalancer
