kind: PersistentVolume
apiVersion: v1
metadata:
  name: www-vol1
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: www-vol1
    fsType: ext4