apiVersion: v1
kind: Service
metadata:
  labels:
    app: app1
  name: app1-svc
  namespace: default
spec:
  ports:
  - name: serve
    port: 80
    targetPort: serve
  selector:
      app: app1
  type: NodePort
