apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app
  namespace: app1
  labels:
      app: app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: deploy
        image: nginx:latest
        ports:
        - name: serve
          containerPort: 80